name: Generate assets structure on PR comment.

on: issue_comment

jobs:
  AddAssetOnGenerate:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '#generate'}}
    steps:
      - name: Get PR branch
        uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch

      - name: Set latest commit status as pending
        uses: myrotvorets/set-commit-status-action@master
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: pending

      - name: Checkout to branch
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}

      - name: Generate
        run: |
          node failingScript.js

      - name: Push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git remote set-url --push origin https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add -A
          if ! git diff-index --quiet HEAD; then
            git commit -m "Generate assets structure"
            git push
          fi
      
      - name: Set latest commit status as ${{ job.status }}
        uses: myrotvorets/set-commit-status-action@master
        if: always()
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}

      - name: Add comment to PR
        uses: actions/github-script@v6
        if: always()
        with:
          script: |
            const {execSync} = require('child_process')
            const name = 'Generating assets structure status';
            const url = '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}';
            const success = '${{ job.status }}' === 'success';
            let diffOutput = '';
            try {
              diffOutput = execSync('git diff --name-only HEAD^').toString()
            } catch (e) {
              console.log('Error getting changed files', e)
            }
            const diffFiles = `\nChanged Files:\n` +  (diffOutput.split('\n').filter(line => line.trim() !== '').map(line => '* ' + line).join('') || 'None')
            const script_output = `\n${{ steps.scriptOutput.outputs.SCRIPT_OUTPUT }}`;
            const body = `${name}: ${success ? 'succeeded ✅' : 'failed ❌'}\n${url}${diffFiles}${script_output}`;

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            })

